<a href="https://colab.research.google.com/github/ElenaBara21/TensorFlow/blob/main/00_TensorFlow_funamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#In this tensorflow we are going to cover tensorflow fundamentals



more specifically we are going to cover:


*   intro to tensors
*   getting info from tensorflow
*   manipulating tensors
*   tensors and numpy
*   using @tf.function(a way to spead up your regular python fuctions)
*   Using GPU with TensorFlow(or TPUs)
*   Exercose to try for yourself



**Introduction to Tensors**

In [1]:
#Import TensorFlow
import tensorflow as tf
print(tf.__version__)


2.8.0


In [2]:
#Create tensors with tf,constant()
#for help command shift space
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#check the number of dimension(ndim stands for number of dimensions)
scalar.ndim

0

In [5]:
#create a vector 
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
#Check the dimension of our vector
vector.ndim

1

In [7]:
#create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [11]:
#create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8.,9.]], dtype=tf.float16) #specify the data type parameters

In [12]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [13]:
another_matrix.ndim

2

In [16]:
#lets create a tensor
tensor = tf.constant([[[1, 2, 3,],
                       [4, 5, 6]],
                       [[7,8, 9],
                        [10, 11, 12]],
                       [[13,14,15],
                        [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [17]:
tensor.ndim

3

what we created so far:


*   Scalar: a single number
*   Vector: a number with direction(e.g. wind speed and direction)
*   Matrix: a 2 dimensional array of numbers
*   Tensor: an n-dimensional array of numbers(when n can be any number, a 0-dimensional tensor is a scalar, a 1 dimensional tensor is a vector)



